// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import React from 'react';
import { shadcnComponents } from '@json-render/shadcn';
import { useStateStore } from '@json-render/react';
import type { ComponentType } from 'react';

// Import custom components from the components directory (one component per file)
import MetricCard from './components/MetricCard';
import GameCardCarousel from './components/GameCardCarousel';

// ── Adapter: ComponentRenderProps → BaseComponentProps ──────────────────────
function adapt(Comp: ComponentType<any>): ComponentType<any> {
  const Adapted: ComponentType<any> = ({ element, children, emit, on, bindings, loading }: any) => {
    let store: any;
    try {
      store = useStateStore();
    } catch {
      store = null;
    }

    // Intercept button press to auto-close modals and trigger state updates
    const customEmit = (eventName: string, ...args: any[]) => {
      if (eventName === 'press' && store) {
        const id = element?.props?.id ?? '';
        const label = element?.props?.label ?? '';
        const isClosingAction =
          label === '取消' ||
          label === '儲存' ||
          label === '確認刪除' ||
          label === 'OK' ||
          label === 'Resume Game' ||
          label === 'Quit to Lobby' ||
          id.includes('cancel') ||
          id.includes('submit') ||
          id.includes('confirm') ||
          id.includes('dismiss');
        if (isClosingAction) {
          const modals = store.get('/modals') || {};
          store.set(
            '/modals',
            Object.fromEntries(Object.keys(modals).map((k) => [k, false]))
          );
        }
      }
      if (emit) emit(eventName, ...args);
    };

    let resolvedProps: any = { ...(element?.props ?? {}) };

    if (store) {
      // Evaluate raw props with $bindState or $state
      Object.entries(resolvedProps).forEach(([key, val]: [string, any]) => {
        if (typeof val === 'object' && val !== null) {
          if ('$bindState' in val) {
            resolvedProps[key] = store.get(val.$bindState);
          } else if ('$state' in val) {
            resolvedProps[key] = store.get(val.$state);
          }
        }
      });

      // Evaluate bindings passed from Renderer
      if (bindings) {
        Object.entries(bindings).forEach(([key, val]: [string, any]) => {
          if (val !== undefined && val !== null && key !== 'openPath') {
            if (typeof val === 'string' && val.startsWith('/')) {
              resolvedProps[key] = store.get(val);
            } else if (typeof val === 'object' && val !== null && '$bindState' in val) {
              resolvedProps[key] = store.get((val as any).$bindState);
            } else {
              resolvedProps[key] = val;
            }
          }
        });
      }
    }

    return React.createElement(Comp, {
      props: resolvedProps,
      children,
      emit: customEmit,
      on,
      bindings,
      loading,
    });
  };
  Adapted.displayName = `Adapted(${(Comp as any).displayName || Comp.name || 'Component'})`;
  return Adapted;
}

// ── Component Registry ──────────────────────────────────────────────────────
export const componentRegistry: Record<string, ComponentType<any>> = {
  // ── 1. All @json-render/shadcn presets, adapted ─────────────────────────
  ...Object.fromEntries(
    Object.entries(shadcnComponents).map(([key, Comp]) => [
      key,
      adapt(Comp as ComponentType<any>),
    ])
  ),

  // ── 2. Custom layout shell ───────────────────────────────────────────────
  'Container:page': ({ children }: any) =>
    React.createElement('div', { className: 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6' }, children),

  // ── 3. Custom composites (imported from src/json-render/components/) ─────
  MetricCard: adapt(MetricCard),
  GameCardCarousel: adapt(GameCardCarousel),

  // ── 4. Native HTML passthrough ───────────────────────────────────────────
  div: ({ element, children }: any) =>
    React.createElement('div', { className: element?.props?.className }, children),
};
