// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/api-contracts/openapi.yaml (operationId: insertCoin)

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export interface InsertCoinPayload {
  gameCardId: string;
  playerId: string;
}

export interface OperationStatus {
  success: boolean;
  message: string;
  timestamp: string;
}

export function useDeductCredit() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ gameCardId, playerId }: InsertCoinPayload) =>
      api.post<OperationStatus>(`/game-cards/${gameCardId}:insertCoin`, { playerId }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['whoami'] });
      queryClient.invalidateQueries({ queryKey: ['getUserWalletByPlayerId'] });
      queryClient.invalidateQueries({ queryKey: ['listGameCards'] });
    },
  });
}
