// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/api-contracts/openapi.yaml (operationId: grantAdminCredit)

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api-client';
import type { OperationStatus } from './use-deductCredit';

export interface GrantAdminCreditPayload {
  playerId: string;
  userWalletId: string;
  amount: number;
}

export function useGrantAdminCredit() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ playerId, userWalletId, amount }: GrantAdminCreditPayload) =>
      api.post<OperationStatus>(
        `/players/${playerId}/user-wallets/${userWalletId}:grantAdminCredit`,
        { amount }
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['whoami'] });
      queryClient.invalidateQueries({ queryKey: ['getUserWalletByPlayerId'] });
    },
  });
}
