// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/leaderboard_entry_contract.puml (resolver: getTop10Leaderboard)

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface LeaderboardEntryResponse {
  id: string;
  gameCardId: string;
  playerEmail: string;
  score: number;
  submittedAt: string;
  rank?: number;
}

const GET_TOP_10_LEADERBOARD_QUERY = gql`
  query getTop10Leaderboard($gameId: String!) {
    getTop10Leaderboard(gameId: $gameId) {
      id
      gameCardId
      playerEmail
      score
      submittedAt
    }
  }
`;

export const getTop10LeaderboardKeys = {
  all: ['getTop10Leaderboard'] as const,
  detail: (gameId?: string) => ['getTop10Leaderboard', gameId] as const,
};

export function useGetTop10Leaderboard(gameId?: string) {
  return useQuery({
    queryKey: getTop10LeaderboardKeys.detail(gameId),
    queryFn: () =>
      request<{ getTop10Leaderboard: LeaderboardEntryResponse[] }>(
        GRAPHQL_ENDPOINT,
        GET_TOP_10_LEADERBOARD_QUERY,
        { gameId }
      ).then((data) =>
        data.getTop10Leaderboard.map((item, index) => ({
          ...item,
          rank: index + 1,
        }))
      ),
    enabled: !!gameId,
  });
}
