// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/api-contracts/openapi.yaml (operationId: whoami)

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export interface UserWalletResponse {
  id: string;
  playerId: string;
  dailyFreeCredit: number;
  adminBonusCredit: number;
  totalCredits: number;
  lastDailyResetTime: string;
  version: number;
}

export interface PlayerResponse {
  id: string;
  gcpIapEmail: string;
  createdAt: string;
  wallet?: UserWalletResponse;
}

export const whoamiKeys = {
  all: ['whoami'] as const,
};

export function useWhoami() {
  return useQuery({
    queryKey: whoamiKeys.all,
    queryFn: () => api.post<PlayerResponse>('/players:whoami'),
  });
}
