// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/user_wallet_contract.puml (resolver: getUserWalletByPlayerId)

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';
import type { UserWalletResponse } from './use-whoami';

const GET_USER_WALLET_BY_PLAYER_ID_QUERY = gql`
  query getUserWalletByPlayerId($playerId: String!) {
    getUserWalletByPlayerId(playerId: $playerId) {
      id
      playerId
      dailyFreeCredit
      adminBonusCredit
      totalCredits
      lastDailyResetTime
      version
    }
  }
`;

export const getUserWalletByPlayerIdKeys = {
  all: ['getUserWalletByPlayerId'] as const,
  detail: (playerId?: string) => ['getUserWalletByPlayerId', playerId] as const,
};

export function useGetUserWalletByPlayerId(playerId?: string) {
  return useQuery({
    queryKey: getUserWalletByPlayerIdKeys.detail(playerId),
    queryFn: () =>
      request<{ getUserWalletByPlayerId: UserWalletResponse }>(
        GRAPHQL_ENDPOINT,
        GET_USER_WALLET_BY_PLAYER_ID_QUERY,
        { playerId }
      ).then((data) => data.getUserWalletByPlayerId),
    enabled: !!playerId,
  });
}
