// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/api-contracts/openapi.yaml (operationId: submitHighScore)

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export interface SubmitHighScorePayload {
  gameCardId: string;
  playerEmail: string;
  score: number;
}

export interface LeaderboardEntryResponse {
  id: string;
  gameCardId: string;
  playerEmail: string;
  score: number;
  submittedAt: string;
}

export function useSubmitHighScore() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ gameCardId, playerEmail, score }: SubmitHighScorePayload) =>
      api.post<LeaderboardEntryResponse>(`/game-cards/${gameCardId}/leaderboard-entries`, {
        playerEmail,
        score,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['getTop10Leaderboard'] });
    },
  });
}
