// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/game_card_contract.puml (resolver: listGameCards)

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface GameCardResponse {
  id: string;
  gameId: string;
  title: string;
  coverArtUrl: string;
  description: string;
  totalPlayCount: number;
}

const LIST_GAME_CARDS_QUERY = gql`
  query listGameCards {
    listGameCards {
      id
      gameId
      title
      coverArtUrl
      description
      totalPlayCount
    }
  }
`;

export const listGameCardsKeys = {
  all: ['listGameCards'] as const,
};

export function useListGameCards() {
  return useQuery({
    queryKey: listGameCardsKeys.all,
    queryFn: () =>
      request<{ listGameCards: GameCardResponse[] }>(
        GRAPHQL_ENDPOINT,
        LIST_GAME_CARDS_QUERY
      ).then((data) => data.listGameCards),
  });
}
